package io.ferridian.shim;

import io.ferridian.shim.contract.FerridianContract;
import net.fabricmc.api.ClientModInitializer;

/**
 * Entry point for the Ferridian shim.
 *
 * <p>The shim's whole job is to publish per-frame state to the engine over
 * the versioned contract in {@link io.ferridian.shim.contract}. Everything in
 * that package is generated by {@code tools/shim-codegen}; never edit it by
 * hand.
 *
 * <p>The camera transport is live: when {@link #LAYER_LIB_ENV} names the
 * layer cdylib, it is {@code System.load}ed (the JVM's own dlopen of the
 * same .so the Vulkan loader maps — one set of process globals, so {@link
 * io.ferridian.shim.contract.NativeBridge#publishCamera} lands in the exact
 * store the layer's compositor reads) and a {@link CameraPublisher} feeds it
 * real sun/time/clip-plane state. Without the env var the shim only logs —
 * a vanilla launch stays vanilla.
 */
public final class FerridianShim implements ClientModInitializer {
    /** Absolute path of the Ferridian Vulkan layer cdylib to bind against. */
    static final String LAYER_LIB_ENV = "FERRIDIAN_LAYER_LIB";

    @Override
    public void onInitializeClient() {
        System.out.println(
                "[ferridian-shim] contract v" + FerridianContract.CONTRACT_VERSION
                        + " for Minecraft " + FerridianContract.MINECRAFT_VERSION
                        + " (" + FerridianContract.PASSES.size() + " passes)");
        String layerLib = System.getenv(LAYER_LIB_ENV);
        if (layerLib == null || layerLib.isEmpty()) {
            System.out.println(
                    "[ferridian-shim] " + LAYER_LIB_ENV
                            + " not set; camera transport disabled (packs see placeholder camera)");
            return;
        }
        try {
            System.load(layerLib);
        } catch (UnsatisfiedLinkError error) {
            System.err.println(
                    "[ferridian-shim] failed to load layer cdylib from " + layerLib
                            + ": " + error.getMessage());
            return;
        }
        System.out.println("[ferridian-shim] layer cdylib bound; starting camera publisher");
        CameraPublisher.start();
    }
}
