//! Renders the Java side of the Java↔Rust contract. The shim is ~90%
//! generated; humans edit `crates/contract`, never the emitted files.

use ferridian_contract::{CameraUniforms, Contract, GamePassKind};

pub const JAVA_PACKAGE: &str = "io.ferridian.shim.contract";
pub const GENERATED_DIR: &str = "io/ferridian/shim/contract";

const HEADER: &str = "\
// GENERATED by tools/shim-codegen — DO NOT EDIT.
// Source of truth: crates/contract (Rust). Regenerate: cargo run -p shim-codegen
";

/// Render all generated Java files as (path-relative-to-source-root, content).
pub fn render_java(contract: &Contract) -> Vec<(String, String)> {
    vec![
        (
            format!("{GENERATED_DIR}/GamePassKind.java"),
            render_pass_kind_enum(),
        ),
        (
            format!("{GENERATED_DIR}/FerridianContract.java"),
            render_contract_class(contract),
        ),
        (
            format!("{GENERATED_DIR}/CameraUniforms.java"),
            render_camera_record(),
        ),
    ]
}

fn java_enum_name(kind: GamePassKind) -> String {
    kind.as_str().to_uppercase()
}

fn render_pass_kind_enum() -> String {
    let mut out = String::from(HEADER);
    out.push_str(&format!("package {JAVA_PACKAGE};\n\n"));
    out.push_str(
        "/** Semantic classification of a game render pass. */\npublic enum GamePassKind {\n",
    );
    for kind in GamePassKind::ALL {
        out.push_str(&format!(
            "    {}(\"{}\"),\n",
            java_enum_name(kind),
            kind.as_str()
        ));
    }
    out.push_str(
        "    ;\n\n    private final String wireName;\n\n    GamePassKind(String wireName) {\n        this.wireName = wireName;\n    }\n\n    public String wireName() {\n        return wireName;\n    }\n}\n",
    );
    out
}

fn render_contract_class(contract: &Contract) -> String {
    let mut out = String::from(HEADER);
    out.push_str(&format!("package {JAVA_PACKAGE};\n\n"));
    out.push_str("import java.util.List;\n\n");
    out.push_str("/** Constants and pass metadata shared with the Rust engine. */\n");
    out.push_str("public final class FerridianContract {\n");
    out.push_str(&format!(
        "    public static final int CONTRACT_VERSION = {};\n",
        contract.version
    ));
    out.push_str(&format!(
        "    public static final String MINECRAFT_VERSION = \"{}\";\n\n",
        contract.minecraft_version
    ));
    out.push_str("    public record PassDescriptor(GamePassKind kind, String gameAnchor) {}\n\n");
    out.push_str("    public static final List<PassDescriptor> PASSES = List.of(\n");
    let entries: Vec<String> = contract
        .passes
        .iter()
        .map(|pass| {
            format!(
                "        new PassDescriptor(GamePassKind.{}, \"{}\")",
                java_enum_name(pass.kind),
                pass.game_anchor
            )
        })
        .collect();
    out.push_str(&entries.join(",\n"));
    out.push_str("\n    );\n\n    private FerridianContract() {}\n}\n");
    out
}

fn java_field_name(snake: &str) -> String {
    let mut out = String::with_capacity(snake.len());
    let mut upper_next = false;
    for c in snake.chars() {
        if c == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// The Java mirror of `CameraUniforms`, rendered from the contract's
/// std140 field table so the two encoders cannot drift.
fn render_camera_record() -> String {
    let fields: Vec<(String, usize)> = CameraUniforms::STD140_FIELDS
        .iter()
        .map(|(name, offset)| (java_field_name(name), *offset))
        .collect();
    let mut out = String::from(HEADER);
    out.push_str(&format!("package {JAVA_PACKAGE};\n\n"));
    out.push_str("import java.nio.ByteBuffer;\nimport java.nio.ByteOrder;\n\n");
    out.push_str(
        "/** Per-frame camera and sun state published to the engine (std140 layout). */\n",
    );
    out.push_str("public record CameraUniforms(\n");
    let components: Vec<String> = fields
        .iter()
        .map(|(name, _)| format!("        float {name}"))
        .collect();
    out.push_str(&components.join(",\n"));
    out.push_str(") {\n");
    out.push_str(&format!(
        "    public static final int STD140_SIZE = {};\n\n",
        CameraUniforms::STD140_SIZE
    ));
    out.push_str(
        "    /** Encode at the contract's std140 offsets (little-endian). */\n    public void writeStd140(ByteBuffer buffer) {\n        buffer.order(ByteOrder.LITTLE_ENDIAN);\n",
    );
    for (name, offset) in &fields {
        out.push_str(&format!("        buffer.putFloat({offset}, {name});\n"));
    }
    out.push_str("    }\n}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_java_is_stable() {
        let files = render_java(&Contract::current());
        assert_eq!(files.len(), 3);
        for (path, content) in &files {
            insta::assert_snapshot!(path.replace('/', "_"), content);
        }
    }

    #[test]
    fn every_pass_kind_appears_in_the_enum() {
        let (_, enum_src) = &render_java(&Contract::current())[0];
        for kind in GamePassKind::ALL {
            assert!(enum_src.contains(&java_enum_name(kind)));
        }
    }
}
