[package]
name = "ferridian-vk-layer"
description = "Vulkan layer interception shell — as thin as physics allows"
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
ash = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
