//! Single source of truth for the Java↔Rust contract.
//!
//! The Fabric shim publishes pass metadata (which game pipeline corresponds to
//! terrain, entities, …) to the engine over this versioned contract. The Java
//! side of the contract is *generated* from these definitions by
//! `tools/shim-codegen`; nothing else may define the wire format.
//!
//! The contract is regenerated per Minecraft version — mechanically, from the
//! unobfuscated sources — so version drift is detected, never guessed at.

use serde::{Deserialize, Serialize};

/// Bumped whenever the wire format or the meaning of any field changes.
/// Both sides refuse to talk across a version mismatch.
pub const CONTRACT_VERSION: u32 = 1;

/// Semantic classification of a game render pass, as published by the shim.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GamePassKind {
    Sky,
    Terrain,
    Entities,
    BlockEntities,
    Particles,
    Weather,
    Translucent,
    Hand,
    Gui,
    /// A pass the shim could not classify. The engine must render it
    /// unmodified — unknown never means "drop".
    Unknown,
}

impl GamePassKind {
    /// Every variant, in wire order. Codegen and exhaustiveness tests key off this.
    pub const ALL: [GamePassKind; 10] = [
        GamePassKind::Sky,
        GamePassKind::Terrain,
        GamePassKind::Entities,
        GamePassKind::BlockEntities,
        GamePassKind::Particles,
        GamePassKind::Weather,
        GamePassKind::Translucent,
        GamePassKind::Hand,
        GamePassKind::Gui,
        GamePassKind::Unknown,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            GamePassKind::Sky => "sky",
            GamePassKind::Terrain => "terrain",
            GamePassKind::Entities => "entities",
            GamePassKind::BlockEntities => "block_entities",
            GamePassKind::Particles => "particles",
            GamePassKind::Weather => "weather",
            GamePassKind::Translucent => "translucent",
            GamePassKind::Hand => "hand",
            GamePassKind::Gui => "gui",
            GamePassKind::Unknown => "unknown",
        }
    }
}

/// One pass the shim knows how to identify in the current Minecraft version.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PassDescriptor {
    pub kind: GamePassKind,
    /// The game-side anchor the shim uses to identify this pass (a render
    /// pipeline/stage name in the unobfuscated sources). Regenerated per
    /// Minecraft version by upstream tooling.
    pub game_anchor: String,
}

/// The full contract document exchanged between shim and engine.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Contract {
    pub version: u32,
    /// Minecraft version(s) the `game_anchor`s were derived from.
    pub minecraft_version: String,
    pub passes: Vec<PassDescriptor>,
}

/// Per-frame camera and sun state the shim publishes to the engine, and the
/// engine uploads to packs as the `camera` uniform block.
///
/// The GPU-side layout is **std140** and is part of the contract: pack
/// shaders declare `ConstantBuffer<Camera>` with exactly these members in
/// this order, and [`CameraUniforms::to_std140_bytes`] is the one encoder
/// (offsets 0 / 12 / 16 / 20 — a `float3` aligns to 16 and the following
/// scalar packs into its tail). The Java mirror is generated by
/// `tools/shim-codegen`; transport from the shim lands with the shim IPC,
/// so nothing here changes the current wire format.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CameraUniforms {
    /// Unit vector toward the sun, view space (world space once the shim
    /// publishes real transforms).
    pub sun_direction: [f32; 3],
    /// Seconds since level load; drives animated effects.
    pub time_seconds: f32,
    pub near_plane: f32,
    pub far_plane: f32,
}

impl CameraUniforms {
    /// std140 size of the `Camera` block: members end at byte 24, and the
    /// block rounds up to a 16-byte multiple.
    pub const STD140_SIZE: usize = 32;

    /// The block's scalar fields in declaration order with their std140 byte
    /// offsets. [`CameraUniforms::to_std140_bytes`] writes through this table
    /// and `tools/shim-codegen` renders the Java mirror from it, so the two
    /// encoders cannot drift.
    pub const STD140_FIELDS: [(&'static str, usize); 6] = [
        ("sun_direction_x", 0),
        ("sun_direction_y", 4),
        ("sun_direction_z", 8),
        ("time_seconds", 12),
        ("near_plane", 16),
        ("far_plane", 20),
    ];

    /// Scalar values in [`CameraUniforms::STD140_FIELDS`] order.
    pub fn scalars(&self) -> [f32; 6] {
        [
            self.sun_direction[0],
            self.sun_direction[1],
            self.sun_direction[2],
            self.time_seconds,
            self.near_plane,
            self.far_plane,
        ]
    }

    /// The values packs were built against before the shim publishes real
    /// state: a fixed high sun and Minecraft-shaped clip planes.
    pub fn placeholder() -> CameraUniforms {
        let sun = [0.35f32, 0.9, 0.2];
        let len = (sun[0] * sun[0] + sun[1] * sun[1] + sun[2] * sun[2]).sqrt();
        CameraUniforms {
            sun_direction: [sun[0] / len, sun[1] / len, sun[2] / len],
            time_seconds: 0.0,
            near_plane: 0.05,
            far_plane: 512.0,
        }
    }

    /// Encode for upload to a uniform buffer, little-endian std140.
    pub fn to_std140_bytes(&self) -> [u8; CameraUniforms::STD140_SIZE] {
        let mut bytes = [0u8; CameraUniforms::STD140_SIZE];
        for ((_, offset), value) in CameraUniforms::STD140_FIELDS.iter().zip(self.scalars()) {
            bytes[*offset..offset + 4].copy_from_slice(&value.to_le_bytes());
        }
        bytes
    }
}

#[derive(Debug, thiserror::Error)]
pub enum ContractError {
    #[error("failed to parse contract: {0}")]
    Parse(#[from] toml::de::Error),
    #[error("failed to serialize contract: {0}")]
    Serialize(#[from] toml::ser::Error),
    #[error("contract version mismatch: ours {ours}, theirs {theirs}")]
    VersionMismatch { ours: u32, theirs: u32 },
}

impl Contract {
    /// The canonical contract for the Minecraft version we currently track.
    ///
    /// `game_anchor` values are placeholders until pass detection lands (M2);
    /// the *shape* of this data is what codegen and the shim build against.
    pub fn current() -> Contract {
        Contract {
            version: CONTRACT_VERSION,
            minecraft_version: "26.2".to_owned(),
            passes: GamePassKind::ALL
                .iter()
                .map(|&kind| PassDescriptor {
                    kind,
                    game_anchor: format!("todo/{}", kind.as_str()),
                })
                .collect(),
        }
    }

    pub fn to_toml(&self) -> Result<String, ContractError> {
        Ok(toml::to_string_pretty(self)?)
    }

    pub fn from_toml(text: &str) -> Result<Contract, ContractError> {
        let contract: Contract = toml::from_str(text)?;
        if contract.version != CONTRACT_VERSION {
            return Err(ContractError::VersionMismatch {
                ours: CONTRACT_VERSION,
                theirs: contract.version,
            });
        }
        Ok(contract)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_through_toml() {
        let contract = Contract::current();
        let text = contract.to_toml().unwrap();
        assert_eq!(Contract::from_toml(&text).unwrap(), contract);
    }

    #[test]
    fn rejects_version_mismatch() {
        let mut contract = Contract::current();
        contract.version = CONTRACT_VERSION + 1;
        let text = toml::to_string_pretty(&contract).unwrap();
        assert!(matches!(
            Contract::from_toml(&text),
            Err(ContractError::VersionMismatch { .. })
        ));
    }

    #[test]
    fn camera_encodes_at_the_contract_std140_offsets() {
        let camera = CameraUniforms {
            sun_direction: [1.0, 2.0, 3.0],
            time_seconds: 4.0,
            near_plane: 5.0,
            far_plane: 6.0,
        };
        let bytes = camera.to_std140_bytes();
        assert_eq!(bytes.len(), CameraUniforms::STD140_SIZE);
        // Offsets are the contract: slangc lays `Camera` out exactly so
        // (verified against compiled SPIR-V OpMemberDecorate Offsets).
        let read = |offset: usize| {
            f32::from_le_bytes(bytes[offset..offset + 4].try_into().expect("4 bytes"))
        };
        assert_eq!(read(0), 1.0);
        assert_eq!(read(4), 2.0);
        assert_eq!(read(8), 3.0);
        assert_eq!(read(12), 4.0);
        assert_eq!(read(16), 5.0);
        assert_eq!(read(20), 6.0);
        // The block tail is padding, deterministically zero.
        assert_eq!(&bytes[24..], &[0u8; 8]);
    }

    #[test]
    fn placeholder_camera_sun_is_a_unit_vector() {
        let sun = CameraUniforms::placeholder().sun_direction;
        let len = (sun[0] * sun[0] + sun[1] * sun[1] + sun[2] * sun[2]).sqrt();
        assert!((len - 1.0).abs() < 1e-6, "sun length {len}");
    }

    #[test]
    fn all_variants_have_unique_wire_names() {
        let mut names: Vec<_> = GamePassKind::ALL.iter().map(|k| k.as_str()).collect();
        names.sort_unstable();
        names.dedup();
        assert_eq!(names.len(), GamePassKind::ALL.len());
    }
}
